#### Exercise 1
Given a 2D Numpy array, `pollution_data`, representing daily air quality index values of a city for a week(rows for days and colums for different pollutants), write a code snippet to return the day(row) with the higest average pollution level.

`pollution_data` = np.array([[45, 65, 70], [55, 60, 50], [60, 58, 67]])

In [1]:
import numpy as np

In [13]:
pollution_data = np.array([[45, 65, 70], [55, 60, 50], [60, 58, 67]])

# Calculating the Average pollution level across the rows
avg_pollution_level_row = np.average(pollution_data, axis=1)

# Calculating the maximum average pollution levels across the rows
maximum_pollution_level_row = np.argmax(avg_pollution_level_row)

# print result
print(f"The index of maximum average pollution level is: {maximum_pollution_level_row}")
print(f"The values are: {pollution_data[maximum_pollution_level_row]}")





The index of maximum average pollution level is: 2
The values are: [60 58 67]


#### Exercise 2
A forest department is monitoring deforestation by analysing satellite data of five similarly sized regions. When the monitoring started, each region had full forest coverage (i.e. 100). The most recent data collected has been stored in a 1D NumPy array, `forest_coverage`, where each element represents the percentage of forest cover in different regions. Write code to calculate the total percentage of coverage **lost**, if each 1% reduction in forest cover equals 100 square kilometres.

forest_coverage = np.array([70, 80, 65, 90, 85])

In [22]:
forest_coverage = np.array([70, 80, 65, 90, 85])

# Calculating the coverage lost in sq and percentages
coverage_lost_sq = (100 - forest_coverage).sum() * 100 # in square kilometers
coverage_lost_per = (((100 - forest_coverage).sum()) / 500) * 100

# Print result
print(f"Total forest lost in square kilometer: {round(coverage_lost_sq)} sq")
print(f"Total forest lost in percentage: {round(coverage_lost_per)} %")


Total forest lost in square kilometer: 11000 sq
Total forest lost in percentage: 22 %


#### Exercise 3

For a study on water conservation, we have a 2D NumPy array, `water_quality`, representing different water quality parameters (columns) for various water bodies (rows). Write code to find the water body index (row index) with the worst average quality parameter.

water_quality = np.array([[7.8, 6.5, 8.0], [5.4, 7.2, 6.5]])

In [32]:
water_quality = np.array([[7.8, 6.5, 8.0], [5.4, 7.2, 6.5]])

# Calculating the worst average quality parameter
worst_avg_quality_parameter = np.argmin(water_quality.mean(axis=1))

# Printing results
print(f"Index of worst average quality parameter: {worst_avg_quality_parameter}")
print(f"Values of worst average quality parameter: {water_quality[worst_avg_quality_parameter]}")

Index of worst average quality parameter: 1
Values of worst average quality parameter: [5.4 7.2 6.5]


#### Exercise 4

Biologists tracking caracal movement have recorded the number of caracals spotted in different regions in a 2D NumPy array, `animal_sightings`. Each row represents a different region, and columns represent different days. Write a code snippet to find the index of the region with the highest average number of sightings.

animal_sightings = np.array([[5, 7, 8], [3, 4, 6], [9, 10, 7]])

In [33]:
animal_sightings = np.array([[5, 7, 8], [3, 4, 6], [9, 10, 7]])

# Calculating the index with the highest average number of sightings
highest_average_sightings_index = np.argmax(animal_sightings.mean(axis=1))

# Printing result
print(f"Index with highest average sightings: {highest_average_sightings_index}")

Index with highest average sightings: 2


#### Exercise 5

`np.reshape()` allows us to change the shape of an array without changing its data. For example, we can reshape a 1D array into a 2D array (matrix) or vice versa, as long as the total number of elements remains the same. Remember to read more about functions in the NumPy documentation if anything is unclear.

Biologists have collected data on bird sightings in a region over a month, stored in a 1D NumPy array where each element represents the number of sightings on a particular day. Reshape this data into a 2D array (matrix) representing weeks and days (assume 4 weeks in a month, 7 days per week), and calculate the total sightings for each week.

bird_sightings = np.array([3, 4, 2, 5, 1, 0, 4, 3, 5, 2, 1, 7, 8, 1, 2, 3, 4, 1, 0, 5, 6, 2, 3, 4, 1, 4, 6, 7])

In [47]:
bird_sightings = np.array([3, 4, 2, 5, 1, 0, 4, 3, 5, 2, 1, 7, 8, 1, 2, 3, 4, 1, 0, 5, 6, 2, 3, 4, 1, 4, 6, 7])

# Reshaping bird sights into 4 weeks and 7 months
reshaped_bird_sightings = bird_sightings.reshape(4, 7)

# Calculating the total bird sightings
Total_sightings = np.sum(reshaped_bird_sightings, axis=1)

print(f"Bird sightings:")
print(reshaped_bird_sightings)

print(f"\nTotal sightings each week:")
print(Total_sightings)

Bird sightings:
[[3 4 2 5 1 0 4]
 [3 5 2 1 7 8 1]
 [2 3 4 1 0 5 6]
 [2 3 4 1 4 6 7]]

Total sightings each week:
[19 27 21 27]


#### Exercise 6

`np.transpose()` is a NumPy function that flips a matrix over its diagonal, switching the row and column indices of the array. This means that the first row becomes the first column, the second row becomes the second column, and so on.

Meteorologists have recorded temperature and precipitation data over a year in a 2D array (rows for months, columns for temperature and precipitation). Transpose the array so that rows represent temperature and precipitation, and columns represent months. Then calculate the average temperature and precipitation over the year.

climate_data = np.array([[22, 50], [25, 43], [28, 35], [30, 20], [27, 25], [25, 30], [23, 40], [24, 55], [22, 60], [20, 65], [18, 70], [22, 58]])

In [63]:
climate_data = np.array([[22, 50], [25, 43], [28, 35], [30, 20], [27, 25], [25, 30], [23, 40], [24, 55], [22, 60], [20, 65], [18, 70], [22, 58]])

# Transposing climate data
climate_data_transposed = np.transpose(climate_data)

# Calculating average temperature and precipitation
avg__temp_preci = np.average(climate_data_transposed, axis=1)

print(f"Transposed Climate data:")
print(climate_data_transposed)
print(f"\nAverage temperature and precipitation:")
print(f"1. Average temperature: {round(avg__temp_preci[0], 2)}")
print(f"2. Average precipitation: {round(avg__temp_preci[1], 2)}")

Transposed Climate data:
[[22 25 28 30 27 25 23 24 22 20 18 22]
 [50 43 35 20 25 30 40 55 60 65 70 58]]

Average temperature and precipitation:
1. Average temperature: 23.83
2. Average precipitation: 45.92
